name: Fly Deploy
on:
  push:
    branches:
      - main # or master, whichever your default branch is
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --local-only # Changed from --remote-only to --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
